// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/diegoholiveira/bookstore-sample/users"
	mock "github.com/stretchr/testify/mock"
)

// UserRegister is an autogenerated mock type for the UserRegister type
type UserRegister struct {
	mock.Mock
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *UserRegister) Register(_a0 context.Context, _a1 *users.User) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
