// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserConstraints is an autogenerated mock type for the UserConstraints type
type UserConstraints struct {
	mock.Mock
}

// EmailIsUsed provides a mock function with given fields: _a0, _a1
func (_m *UserConstraints) EmailIsUsed(_a0 context.Context, _a1 string) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
