// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/diegoholiveira/bookstore-sample/users"
	mock "github.com/stretchr/testify/mock"
)

// WelcomeMailer is an autogenerated mock type for the WelcomeMailer type
type WelcomeMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *WelcomeMailer) Send(_a0 context.Context, _a1 *users.User) {
	_m.Called(_a0, _a1)
}
