// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package purchaseshistory

import (
	"database/sql"
)

// Injectors from wire.go:

func InitHandler(db *sql.DB) PurchasesHistoryHandler {
	purchasesRepository := NewPurchasesRepository(db)
	purchasesHistoryHandler := NewPurchasesHistoryHandler(purchasesRepository, purchasesRepository)
	return purchasesHistoryHandler
}
