// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	purchases "github.com/diegoholiveira/bookstore-sample/purchases"
)

// Purchaser is an autogenerated mock type for the Purchaser type
type Purchaser struct {
	mock.Mock
}

// MakePurchase provides a mock function with given fields: _a0, _a1
func (_m *Purchaser) MakePurchase(_a0 context.Context, _a1 purchases.Purchase) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, purchases.Purchase) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
