// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-chi/chi"
)

// Injectors from wire.go:

func InitHTTPRouter() chi.Router {
	middlewares := NewMiddlewares()
	router := NewHTTPRouter(middlewares)
	return router
}
