// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package purchasepersister

import (
	"database/sql"
	"github.com/diegoholiveira/bookstore-sample/users/usersregister"
)

// Injectors from wire.go:

func InitHandler(db *sql.DB, mailer usersregister.WelcomeMailer) PurchaseHandler {
	purchaserWithRegisteredUser := NewPurchaserWithRegisteredUser(db)
	userRegisterServiceFactory := NewUserRegisterServiceFactory(mailer)
	purchaserWithNewUser := NewPurchaserWithNewUser(db, userRegisterServiceFactory)
	purchaser := NewPurchaserService(purchaserWithRegisteredUser, purchaserWithNewUser)
	purchaseHandler := NewPurchaseHandler(purchaser)
	return purchaseHandler
}
