// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	users "github.com/diegoholiveira/bookstore-sample/users"
)

// UserFinder is an autogenerated mock type for the UserFinder type
type UserFinder struct {
	mock.Mock
}

// FindUserByID provides a mock function with given fields: _a0, _a1
func (_m *UserFinder) FindUserByID(_a0 context.Context, _a1 uint64) (users.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(context.Context, uint64) users.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
