// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package usersregister

import (
	"database/sql"
)

// Injectors from wire.go:

func InitHandler(db *sql.DB, mailer2 WelcomeMailer) UserRegisterHandler {
	userConstraints := NewUserConstraints(db)
	databasePersister := NewDatabasePersister(db)
	userRegister := NewUserRegisterService(userConstraints, databasePersister, mailer2)
	userRegisterHandler := NewUserRegisterHandler(userRegister)
	return userRegisterHandler
}
