// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package booksretriever

import (
	"database/sql"
)

// Injectors from wire.go:

func InitBooksAvailableHandler(db *sql.DB) BooksAvailableHandler {
	booksFinder := NewBooksRetrieverRepository(db)
	booksAvailableHandler := NewBooksAvailableHandler(booksFinder)
	return booksAvailableHandler
}

func InitBookDetailsHandler(db *sql.DB) BookDetailsHandler {
	booksFinder := NewBooksRetrieverRepository(db)
	bookDetailsHandler := NewBookDetailsHandler(booksFinder)
	return bookDetailsHandler
}
