FORMAT: 1A
HOST: http://localhost:8080

# @diegoholiveira/bookstore-sample

<!-- include(entities.apib) -->
<!-- include(errors.apib) -->
<!-- include(books.apib) -->
<!-- include(users.apib) -->
<!-- include(purchases.apib) -->
