# Data Structures

## Register Bad Request (object)
+ name: `name can not be blank` (string)
+ email: `email can not be blank` (string)
+ password: `password can not be blank` (string)
+ error: `Error while decoding the JSON payload` (string)

## Bad Request (object)
+ error: `Error while decoding the JSON payload` (string)

## Book Not Found (object)
+ error: `Book Not Found` (string)

## User Not Found (object)
+ error: `User Not Found` (string)
